/*K. p. a mediak.txt szoveges allomanybol beolvassa egy osztaly ev vegi mediait,
majd kiirja, hogy hany media van 5-os alatt, 5-5.99, 6-6.99, 7-7.99, 8-8.99, 9-9.99, 10.*/

#include <iostream>
#include <fstream>

using namespace std;

int main()
{
    int v[n];
    float sz;
    
    ifstream file1;

    file1.open("mediak.txt");

    while(!file1.eof()){
        file1 >> sz;
    }
    
    

    






    return 0;
}